### ISSUE TITLE
docs: write a CONTRIBUTING doc file with minimal instructions

### ISSUE THREAD

**Issue by dreamorosi** [saragerion/serverless-voting-app#2]
Hi there, it's me again 🌝 

I'm looking at the repo & I'm trying to deploy the architecture in my AWS account. 

If it's welcome, I would like to create a small `CONTRIBUTING.md` file that explains the minimal steps needed to deploy the app with Terraform.

I'll be writing one for myself so I'm happy to open a PR later to document the steps.

**Comment by saragerion** [comment]
Thanks Andrea, sounds good to me :)

**Comment by dreamorosi** [comment]
Closing for now.

Might pick up this again in the future.
